"""add unique phone constraint

Revision ID: 2967c7871772
Revises: eaf3f565a4e6
Create Date: 2026-07-04 14:36:44.234883

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2967c7871772'
down_revision: Union[str, Sequence[str], None] = 'eaf3f565a4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_player_phone', ['country_code', 'mobile_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint('uq_player_phone', type_='unique')

    # ### end Alembic commands ###
